import type { NextPage } from 'next'
import Head from 'next/head'

import { useAuth } from 'src/hooks'

const Home: NextPage = () => {
  const { signInWithGoogle, signOut } = useAuth()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="block" onClick={signInWithGoogle}>
        login
      </button>
      <button className="block" onClick={signOut}>
        logout
      </button>
    </div>
  )
}

export default Home
